# EDA

## Problem Statement

The Zomato exploratory data analysis aims to assist food enthusiasts in discovering the best restaurants and value-for-money options within their locality. It facilitates locating desired cuisines available nearby. With a dataset encompassing restaurant details like establishment type, address, city, locality, and cuisine offerings, alongside attributes such as average cost for two, price range, and aggregate ratings, the objective is to uncover insights into restaurant preferences and dining trends. Through analyzing factors like average cost, ratings, and customer engagement metrics such as votes and photo counts, this study seeks to provide actionable recommendations for diners seeking satisfying dining experiences.

## Data Definition

**res_id**: The code given to a restaurant (Categorical) 

**name**: Name of the restaurant (Categorical)

**establishment**: Represents the type of establishment (Categorical)

**url**: The website of the restaurant (Categorical)

**address**: The address of the restaurant (Categorical)

**city**: City in which the restaurant located (Categorical)

**city_id**: The code given to a city (Categorical)

**locality**: Locality of the restaurant (Categorical)

**latitude**: Latitude of the restaurant (Categorical)

**longitude**: Longitude of the restaurant (Categorical)

**zipcode**: Zipcode of the city in which the restaurant located (Categorical)

**country_id**: Country code in which the restaurant located (Categorical)

**locality_verbose**: Locality along with the city in which the restaurant located (Categorical)

**cuisines**: The cuisines a restaurant serves (Categorical)

**timings**: The working hours of a restaurant (Categorical)

**average_cost_for_two**: The average amount expected for 2 people (Numerical)

**price_range**: The categories for average cost (Categories - 1,2,3,4) (Categorical)

**currency**: The currency in which a customer pays (Categorical)

**highlights**: The facilities of the restaurant (Categorical)

**aggregate_rating**: The overall rating a restaurant has got (Numerical) 

**rating_text**: Categorized ratings (Categorical)

**votes**: Number of votes received by the restaurant from customers (Numerical)

**photo_count**: The number of photos of a restaurant (Numerical)

**opentable_support**: Restaurant reservation from Opentable (Categorical)

**delivery**: The restaurant deliver an order or not (Categorical)

**takeaway**: The restaurant allows  a 'takeaway' of an order or not (Categorical)

## Table of Contents


1. **[Import Libraries](#import_lib)** 
2. **[Set Options](#set_options)** 
3. **[Read Data](#Read_Data)** 
4. **[Understand  and Prepare the Data](#Understand_Data)**
5. **[Understand the variables](#Understanding_variables)**
6. **[Check for Missing Values](#missing)**
7. **[Study Correlation](#correlation)**
8. **[Detect Outliers](#outliers)**
9. **[Create a new variable 'region'](#region)**
10. **[Some more analysis](#more)** 


# Importing Libraries


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path


import warnings 
warnings.filterwarnings("ignore")

In [2]:
PROJECT_ROOT = Path.cwd().parent
data_path = PROJECT_ROOT / "data" / "train_sample_2024.csv"
data=pd.read_csv(data_path)
df=data.copy()

# Data Understanding

In [3]:
# Checking the number of rows and columns
df.shape

(200000, 24)

In [4]:
# Checking out the basic info of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 200000 non-null  int64  
 1   QUARTER              200000 non-null  int64  
 2   MONTH                200000 non-null  int64  
 3   DAY_OF_WEEK          200000 non-null  int64  
 4   MKT_UNIQUE_CARRIER   200000 non-null  object 
 5   ORIGIN_AIRPORT_ID    200000 non-null  int64  
 6   ORIGIN               200000 non-null  object 
 7   DEST_AIRPORT_ID      200000 non-null  int64  
 8   DEST                 200000 non-null  object 
 9   CRS_DEP_TIME         200000 non-null  int64  
 10  DEP_TIME_BLK         200000 non-null  object 
 11  TAXI_OUT             200000 non-null  float64
 12  TAXI_IN              200000 non-null  float64
 13  CANCELLED            200000 non-null  float64
 14  DIVERTED             200000 non-null  float64
 15  ACTUAL_ELAPSED_TI

In [5]:
# Checking for null values
df.isna().sum()

YEAR                   0
QUARTER                0
MONTH                  0
DAY_OF_WEEK            0
MKT_UNIQUE_CARRIER     0
ORIGIN_AIRPORT_ID      0
ORIGIN                 0
DEST_AIRPORT_ID        0
DEST                   0
CRS_DEP_TIME           0
DEP_TIME_BLK           0
TAXI_OUT               0
TAXI_IN                0
CANCELLED              0
DIVERTED               0
ACTUAL_ELAPSED_TIME    0
AIR_TIME               0
DISTANCE               0
DISTANCE_GROUP         0
CARRIER_DELAY          0
WEATHER_DELAY          0
NAS_DELAY              0
SECURITY_DELAY         0
LATE_AIRCRAFT_DELAY    0
dtype: int64

In [6]:
# Checking duplicates
df.duplicated().sum()

np.int64(0)

In [7]:
# displaying top 5 data
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_WEEK,MKT_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN,DEST_AIRPORT_ID,DEST,CRS_DEP_TIME,...,DIVERTED,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,2,6,3,AA,11057,CLT,13360,MLB,2131,...,0.0,120.0,69.0,490.0,2,0.0,0.0,0.0,0.0,0.0
1,2024,2,4,3,WN,13851,OKC,15016,STL,620,...,0.0,74.0,63.0,462.0,2,0.0,0.0,0.0,0.0,0.0
2,2024,3,8,2,UA,14794,SGU,11292,DEN,1030,...,0.0,122.0,77.0,517.0,3,0.0,0.0,0.0,0.0,0.0
3,2024,3,8,6,B6,10721,BOS,10693,BNA,1353,...,0.0,170.0,143.0,942.0,4,0.0,0.0,0.0,0.0,0.0
4,2024,3,8,7,WN,14057,PDX,13232,MDW,1335,...,0.0,214.0,201.0,1751.0,8,0.0,0.0,0.0,0.0,0.0


## Understanding the variables

In [8]:
df.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_WEEK', 'MKT_UNIQUE_CARRIER',
       'ORIGIN_AIRPORT_ID', 'ORIGIN', 'DEST_AIRPORT_ID', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME_BLK', 'TAXI_OUT', 'TAXI_IN', 'CANCELLED',
       'DIVERTED', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'DISTANCE_GROUP', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY',
       'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY'],
      dtype='object')

In [9]:
for i in df.columns:
    print(i)
    print(df[i].unique())
    print()

YEAR
[2024]

QUARTER
[2 3 4 1]

MONTH
[ 6  4  8 10  5  9  7  1 12  2  3 11]

DAY_OF_WEEK
[3 2 6 7 4 1 5]

MKT_UNIQUE_CARRIER
['AA' 'WN' 'UA' 'B6' 'AS' 'DL' 'HA' 'G4' 'NK' 'F9']

ORIGIN_AIRPORT_ID
[11057 13851 14794 10721 14057 14685 14107 14252 13244 15919 10994 10372
 14843 13377 13930 11298 10397 13342 10693 11066 12982 12889 11292 13204
 14679 12478 13495 14747 11433 13487 12266 14698 15323 12758 13830 14771
 11648 11109 12953 14709 11618 14122 14831 15376 14027 12173 12892 14893
 11278 10800 13871 11193 11259 14783 12945 11624 12954 10713 13303 14262
 14193 10299 11697 13433 10785 11995 10170 10747 14869 13485 14100 13232
 10792 11503 12191 10821 14307 14683 15304 14492 12278 12343 14952 11986
 11996 11637 11140 13577 10466 11423 12339 10868 15016 10620 14321 11233
 10849 11638 14108 14908 15370 11267 10279 11003 10529 11884 10423 11042
 15624 14576 12264 10140 14524 11612 15096 10245 13158 11122 12896 13931
 13296 10980 13795 12402 10257 14730 12519 10431 12335 14574 12451 12129
 

## Checking for missing values

In [10]:
df.isna().sum()

YEAR                   0
QUARTER                0
MONTH                  0
DAY_OF_WEEK            0
MKT_UNIQUE_CARRIER     0
ORIGIN_AIRPORT_ID      0
ORIGIN                 0
DEST_AIRPORT_ID        0
DEST                   0
CRS_DEP_TIME           0
DEP_TIME_BLK           0
TAXI_OUT               0
TAXI_IN                0
CANCELLED              0
DIVERTED               0
ACTUAL_ELAPSED_TIME    0
AIR_TIME               0
DISTANCE               0
DISTANCE_GROUP         0
CARRIER_DELAY          0
WEATHER_DELAY          0
NAS_DELAY              0
SECURITY_DELAY         0
LATE_AIRCRAFT_DELAY    0
dtype: int64

In [ ]:
sns.heatmap(df.isnull(),annot=True,cmap='coolwarm',cbar=False)
plt.show()

KeyboardInterrupt: 

Error in callback <function _draw_all_if_interactive at 0x000001C2D40125C0> (for post_execute), with arguments args (),kwargs {}:


KeyboardInterrupt: 